In [104]:
import pandas as pd

Movie_path = r"C:\Users\adria\Desktop\Python\Machine-learning\labb1\ml-latest\movies.csv"
Rating_path = r"C:\Users\adria\Desktop\Python\Machine-learning\labb1\ml-latest\ratings.csv"
tags_path = r"C:\Users\adria\Desktop\Python\Machine-learning\labb1\ml-latest\tags.csv"

movieDF = pd.read_csv(Movie_path)
ratingsDF = pd.read_csv(Rating_path)
tagsDF = pd.read_csv(tags_path)

ratingsDF.head()

   userId  movieId  rating   timestamp
0       1        1     4.0  1225734739
1       1      110     4.0  1225865086
2       1      158     4.0  1225733503
3       1      260     4.5  1225735204
4       1      356     5.0  1225735119

In [105]:
movieDF.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [106]:
tagsDF.head()

   userId  movieId            tag   timestamp
0      10      260   good vs evil  1430666558
1      10      260  Harrison Ford  1430666505
2      10      260         sci-fi  1430666538
3      14     1221      Al Pacino  1311600756
4      14     1221          mafia  1311600746

In [107]:
shapes = [f"Movie set shape: {movieDF.shape}", 
          f"Ratings set shape: {ratingsDF.shape}",
          f"Tags set shape: {tagsDF.shape}"]
for r in shapes:
    print(r)

Movie set shape: (86537, 3)
Ratings set shape: (33832162, 4)
Tags set shape: (2328315, 4)

In [108]:
movieDF.info()

<class 'pandas.DataFrame'>
RangeIndex: 86537 entries, 0 to 86536
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  86537 non-null  int64
 1   title    86537 non-null  str
 2   genres   86537 non-null  str
dtypes: int64(1), str(2)
memory usage: 2.0 MB

In [109]:
ratingsDF.info()

<class 'pandas.DataFrame'>
RangeIndex: 33832162 entries, 0 to 33832161
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 1.0 GB

In [110]:
print(tagsDF.info())
print("unique tags:", len(tagsDF["tag"].unique()))

<class 'pandas.DataFrame'>
RangeIndex: 2328315 entries, 0 to 2328314
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   tag        str
 3   timestamp  int64
dtypes: int64(3), str(1)
memory usage: 71.1 MB
None
unique tags: 153950

In [111]:
movieDF["year"] = movieDF["title"].str.extract(r"\((\d{4})\)")
movieDF["title"] = movieDF["title"].str.replace(r"\((\d{4})\)", "", regex=True)

movieDF.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [112]:
tagsDF[tagsDF["tag"].isna()].head()

        userId  movieId  tag   timestamp
530012  104413      123  NaN  1199450867
530013  104413      346  NaN  1199451946
530017  104413     1184  NaN  1199452261
530024  104413     1785  NaN  1199452006
530025  104413     2194  NaN  1199450677

In [113]:
tags_grouped = tagsDF.groupby("movieId")["tag"].apply(lambda x: " ".join(x.dropna().astype(str))).reset_index()

tags_grouped.head()

   movieId                                                tag
0        1  animation friendship toys animation Disney Pix...
1        2  animals based on a book fantasy magic board ga...
2        3  sequel moldy old old age old men wedding old p...
3        4  characters chick flick girl movie characters c...
4        5  family pregnancy wedding 4th wall aging baby d...

In [124]:
movieDF["title"] = movieDF["title"].str.strip()

movieDF["title"][0]

'Toy Story'

In [125]:
movieTags = movieDF.merge(tags_grouped, on="movieId", how="left")

movieTags["tag"] = movieTags["tag"].fillna("")
movieTags["year"] = movieTags["year"].fillna("")

movieTags["text"] = (movieTags["title"].astype(str) + " " + 
                     movieTags["year"].astype(str) + " " +
                     movieTags["genres"].astype(str) + " " +
                     movieTags["tag"].astype(str))

movieTags["text"] = (movieTags["text"].str.lower().str.replace("|", " ", regex=False))

movieTags["text"][0]

"toy story 1995 adventure animation children comedy fantasy animation friendship toys animation disney pixar toys cgi classic disney pixar lots of heart tom hanks clever funny pixar witty animation comedy kids pixar tom hanks toy story toys animated fun jealousy funny witty adventure animation comedy family fantasy john lasseter usa family film friendship toys disney dolls national film registry buddy movie tom hanks witty pixar adventure clever enemies become friends family family cartoon family relationships feel-good first of series friends friendship fun fun family movie heroic mission humorous jealousy kids kids movie loyal friend loyalty redemption reflection rescue mission rivalry selflessness teamwork unlikely friendships unusual friendship witty os dois viram adventure animated animation cgi comedy disney family fantasy friendship imdb top 250 pixar tom hanks witty classic disney friendship pixar accepting reality emotional friendship funny soundtrack humorous pixar tumey's to see again tumey's vhs animation pixar action figure action figures buzz lightyear cg animation toy toys woody children computer animation family funny pixar tom hanks toys owned clever computer animation disney tom hanks disney pixar tim allen tom hanks animated animation children comedy fantasy funny humorous pixar time travel funny humorous pixar tom hanks friendship funny pixar tom hanks pixar pixar pixar pixar tom hanks adventure animation classic clever computer animation disney kids pixar redemption tom hanks unlikely friendships unusual friendship animation cgi first cgi film computer animation disney animated feature pixar animation tã©a leoni does not star in this movie animation family sci-fi animation classic pixar family interesting animation pixar pixar animation pixar animation cartoon pixar family computer animation funny pixar action disney kids buddy movie cartoon children clever family friendship kids tom hanks witty cgi animation disney friendship imdb top 250 pixar witty adventure animated animation computer animation disney funny pixar tom hanks toys adventure animated animation buddy movie comedy computer animation disney friendship funny humorous pixar tom hanks witty animated animation buddy movie computer animation funny pixar tom hanks animation pixar toys animation rainy day watchlist animation children computer animation disney imdb top 250 john lasseter pixar tom hanks animation kids movie children pixar tom hanks disney jealousy tom hanks animation comedy funny pixar witty disney funny pixar time travel pixar pixar fun good animation lovable characters computer animation pixar tom hanks avi buy pixar want to see again clever comedy disney family friendship funny humorous pixar tom hanks witty the boys fantasy funny humorous pixar witty animation  buddy movie clever comedy computer animation disney friendship fun funny humorous pixar tom hanks witty classic clever funny tom hanks witty bright daring rescues fanciful heroic mission humorous light rousing toys come to life unlikely friendships warm witty adventure animated animation classic disney fantasy pixar tom hanks toys animation clever comedy funny humorous pixar witty animation computer animation beautiful family villian hurts toys animation disney pixar toys tom hanks adventure animation buddy movie disney friendship pixar tom hanks pixar cgi computer animation animation cgi disney family toys american animation animation clever disney pixar cartoon adventure clever funny tom hanks witty animmation friendship funny toy adventure animation children comedy family friendship funny humorous pixar pixar animation buddy movie computer animation friendship tom hanks disney animation disney friendship pixar animation cartoon children computer animation kids pixar tom hanks want animation pixar comedy digital pixar time travel children computer animation disney family pixar adventure animation buddy movie classic clever comedy friendship fun funny humorous kids pixar toys unusual friendship animation disney pixar animation family tom hanks animation animation pixar pixar animation disney pixar pixar witty adventure animated animation clever comedy computer animation family fantasy tom hanks pixar itaege pixar comedy funny tom hanks comedy toys animated animation buddy movie children clever time travel witty cgi classic children toy toys adventure animated animation cartoon disney family friendship imdb top 250 pixar toy toys animation pixar animation erlend's dvds disney fast and a furious monsters pixar toys soothing adventure animation classic clever comedy computer animation disney friendship funny pixar witty animation classic funny pixar adventure classic funny pixar toys rated-g pixar tim allen tom hanks cartoon computer animation disney humorous pixar friendship pixar toys adventure buddy movie computer animation pixar tom hanks cgi children toys adventure animation computer animation 3d animated children comedy computer animation disney family humorous pixar time travel tom hanks disney favorite pixar kids and family animated children computer animation family pixar toy adventure animation disney funny pixar animation comedy disney pixar pixar witty tom hanks almost favorite family friendship pixar pixar animation humorous pixar time travel animation children disney pixar animated fun family movie pixar animation children fun animation disney pixar witty funny pixar witty imdb top 250 animation pixar pixar disney family family cartoon animated imdb top 250 pixar tom hanks toys animation disney pixar disney children disney computer animation disney fantasy pixar toys witty pixar tom hanks adventure disney animation animation pixar animation cgi comedy computer animation imdb top 250 pixar animation pixar animated animation comedy disney pixar 2009 reissue in stereoscopic 3-d 55 movies every kid should see--entertainment weekly bd-video clv dvd-video adventure animated animation children clever computer animation family friendship funny humorous toys witty disney pixar imdb top 250 witty adventure children family funny animation imdb top 250 pixar animation disney pixar cute funny story voice acting witty friends animation pixar tim allen tom hanks ya boy children comedy funny witty animation children toys animation children disney animation cgi friendship funny pixar tom hanks witty animation cartoon friendship pixar unny adventure clever friendship humorous pixar witty children computer animation family humorous time travel tom hanks witty joss whedon disney pixar animation computer animation pixar toys adventure computer animation pixar animated computer animation family cartoon imdb top 250 animation disney animation children computer animation kids pixar animation comedy funny imdb top 250 pixar animation disney animation fun 1990s 3 dimensional 3d action figure affection alien animated dog animated fictional tv commercial antenna anthropomorphic toy anthropomorphism apology arcade arcade game arm asking directions astronaut audio flashback baby baby monitor backfire backyard bad guy ballet flats banister battery battleship game bed bedroom binoculars biohazard sign birthday birthday party birthday present blinds blockbuster bo peep character bouncy ball boy boy next door brat brawl brother sister relationship bull terrier bully bully comeuppance bullying burn buzz lightyear character calling someone an idiot candy land the board game car car crash card game cartoon dog catchphrase cgi animation character's point of view camera shot chased by a dog chasing a truck child child antagonist child destroys another's toy child destroys own toy child villain child's bedroom child's birthday child's birthday party christmas christmas day christmas present chrysler automobile chrysler lebaron convertible claw crane clock comeuppance comic hero commercial computer animation computer generated imagery confrontation corkboard cowboy cowboy boot cowboy doll crate cult favorite cult film dachshund dart dartboard dead battery delivery dental braces depression desk dinosaur directorial debut disney dog dog as gift doll doorbell double prize doubt elementary school encouragement enemies become friends envy escape escape attempt etch a sketch explosion face mask falling from a window falling from height falling out a window false accusation family relationships famous line famous score famous song favoritism fear fight fireplace first of series first of trilogy first part fishing rod fistfight flashlight flying friend friends friendship frustration game of life board game gas station gift girl gliding globe gratitude guilty conscience hasbro hat heartfelt hero hockey puck home house jack in the box jealousy jumping from height jumping through a sunroof karate karate chop laughter learning a lesson leggings lifting a female into the air lifting someone into the air lipstick on face little boy little girl locked in looking out a window love interest loyalty magic 8 ball magnifying glass male antagonist male protagonist male villain martial arts match mattel medical mask meeting microphone mission misunderstanding mockery mother son relationship mouth moving moving van mr potato head mr. potato head character mutant national film registry neighbor neighborhood nesting egg new home new toy ohio operation game original story package parachute part of trilogy pet as gift pet dog piggy bank pixar pizza van pizzeria plastic army men playskool pliers porcelain poster product placement pterodactyl pull string doll push button radio controlled rag doll rain ramp recliner chair reconnaissance mission redemption reference to marie antoinette reference to mattel reflection rejection remorse remote controlled toy car rescue rescue mission resourcefulness ringing a doorbell rival rivalry rocket running scene before opening credits scene during opening credits scheming seatbelt self awareness selflessness shark shed shepherdess sheriff shivering showdown signature single mother skateboard sleeping dog sliding down a banister slinky dog slow motion scene soldier space explorer space ranger spaceman toy spacesuit squeeze toy staircase storage shed subjective camera suburb sunlight sunroof surgical mask surprise ending surrounded talking in one's sleep talking to a toy talking toy teamwork television commercial telling someone to shut up threat thunder thunderstorm time lapse photography title spoken by character toolbox torture tough guy toy toy animal toy comes to life toy dinosaur toy dog toy fire truck toy robot toy soldier toy story toy tea set toybox toyota toyota truck troll doll troubled production turbo boost twister the game two word title tyrannosaurus rex urban setting utah teapot van ventilation shaft view through binoculars villain violence visual pun walkie talkie wallpaper water weightlifting wilhelm scream window woody character yelling animation children comedy disney friendship funny pixar tom hanks 3d pixar animation pixar pixar disney family pixar tom hanks animation clever friendship funny humorous pixar witty family cartoon animation  clever comedy funny pixar tom hanks toys adventure classic friendship funny animation friendship funny pixar tom hanks witty comedy friendship jealousy clever witty animation funny pixar children comedy friendship pixar pixar pixar funny pixar children family pixar tom hanks toys witty classic comedy fun funny humorous pixar classic pixar witty pixar toys computer animation funny humorous pixar tom hanks witty pixar first of series pixar computer animation pixar best of rotten tomatoes: all time john lasseter animation disney family funny oscar (best picture) engaging comedy hero's journey computer animation pixar pixar tim allen tom hanks adventure childish friendship witty ss so funny very nice classic tom hanks computer animation pixar pixar pixar classic clever witty toys reflection pixar witty animation family good time very good classic friendship pixar children cartoon feel-good funny adventure animation  comedy  computer animation family funny pixar tom hanks clever buddy movie friendship toys children clever pixar comedy imdb top 250 pixar classic disney animation comedy funny computer animation good cartoon chindren pixar pixar 3d children disney pixar pixar watched adventure animated animation buddy movie children classic clever comedy computer animation disney family fantasy funny humorous imdb top 250 pixar time travel tom hanks toys witty pixar pixar adventure animation buddy movie clever comedy cowboy dinosaur dolls friendship funny pixar tim allen tom hanks toys unlikely friendships witty funny disney pixar pixar animation disney funny pixar cartoon https://movielens.org/tag/:animation buddy computer animation directorial debut low fantasy national film registry oscar (special achievement) toys cgi ad for toys children clever forced puns  internal logic fails mixed soundtrack reflection rivalry technological marvel adventure animation disney funny pixar children classic disney fun imdb top 250 kids adventure friendship family animated cgi comedy animation tom hanks animated buddy movie cartoon cgi comedy computer animation family friendship kids toy toys innovative adventure animation  cartoon family great movie cartoon disney animation clever friendship funny tom hanks witty x291-live-john lasseter adventure children classic computer animation disney funny pixar tim allen tom hanks animation fun animation classic comedy computer animation disney funny humorous pixar time travel tom hanks witty pixar toys disney friendship nostalgic animation pixar toys played time travel kids light hearted whimsica animated animation children classic clever comedy computer animation disney friendship funny humorous pixar toys witty adventure animation children comedy exciting plot funny lines touching story children animated comedy disney fun funny pixar tim allen time travel adventure classic clever comedy disney family friendship funny humorous imdb top 250 pixar tom hanks witty pixar unlikely friendships family fun tom hanks friendship pixar children animation children clever disney family funny humorous imdb top 250 pixar pixar animation tom hanks é˜®ä¸€é¸£"

In [126]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    min_df= 2
)

tfidf_matrix = vectorizer.fit_transform(movieTags["text"])

tfidf_matrix.shape

(86537, 300620)

In [127]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def get_similar_movies(movie_index, top_n = 20):
    movie_vector = tfidf_matrix[movie_index]
    similarities = cosine_similarity(movie_vector, tfidf_matrix).flatten()
    similar_indices = similarities.argsort()[::-1][1:top_n+1]
    return similar_indices, similarities[similar_indices]

In [309]:
def get_movie_index(movie_title):
    matches = movieDF.index[movieDF["title"].str.lower() == movie_title.lower()].tolist()

    if not matches:
        raise ValueError(f"The movie title: {movie_title} was not found")
    return matches[0]
    

def get_movie_titles(movie_indices):
    return movieDF.iloc[movie_indices]["title"].tolist()

def rertieval(movie_title, top_n=200):
    movie_indx = get_movie_index(movie_title)

    movie_vector = tfidf_matrix[movie_indx]
    similarities = cosine_similarity(movie_vector, tfidf_matrix).flatten()
    simMovieIndx = similarities.argsort()[::-1][1:top_n+1]

    simMovies = get_movie_titles(simMovieIndx)
    return simMovies, simMovieIndx

inputMovieTitle = "joe somebody"

candidateTitles, candidatesIndx = rertieval(inputMovieTitle)

for movie in candidateTitles[:10]:
    print(movie)

Who Is Cletis Tout?
Tim Allen: Men Are Pigs
Hemel
Slogans
Aamdani Atthanni Kharcha Rupaiya
Memórias Póstumas
10 Attitudes
Kwik Stop
Santa Clause, The
Stakaman!

In [310]:
def get_ratings(movies_byIndex, input_title):

    candidates_Id = movieTags.iloc[movies_byIndex]["movieId"]
    inputMovie_id = movieTags.loc[movieTags["title"].str.lower() == input_title.lower(), "movieId"].iloc[0]
    movies_to_keep = candidates_Id.tolist() + [inputMovie_id]
    candidateRatings = ratingsDF[ratingsDF["movieId"].isin(movies_to_keep)]
    candidateRatings.drop("timestamp", axis=1, inplace=True)
    
    return candidateRatings

In [311]:


candidates_Id = movieTags.iloc[candidatesIndx]["movieId"]

inputMovie_id = movieTags.loc[movieTags["title"].str.lower() == inputMovieTitle.lower(), "movieId"].iloc[0]

movies_to_keep = candidates_Id.tolist() + [inputMovie_id]

candidateRatings = ratingsDF[ratingsDF["movieId"].isin(movies_to_keep)]

candidateRatings.drop("timestamp", axis=1, inplace=True)
candidateRatings.head()

      userId  movieId  rating
116        2      317     3.0
374        7     1485     3.0
1266      21      317     3.0
2018      24      317     4.0
2150      24     1485     4.5

In [312]:
from scipy.sparse import csr_matrix

rows = candidateRatings["userId"].astype("category").cat.codes
cols = candidateRatings["movieId"].astype("category").cat.codes
data = candidateRatings["rating"]

rating_matrix = csr_matrix((data, (rows, cols)))

rating_matrix.shape

(46300, 196)

In [313]:
def build_sparse_matrix(ratings):
    rows = ratings["userId"].astype("category").cat.codes
    cols = ratings["movieId"].astype("category").cat.codes
    data = ratings["rating"]

    return csr_matrix((data, (rows, cols)))

In [314]:
movie_similarity = cosine_similarity(rating_matrix.T)

movie_similarity.shape

(196, 196)

In [315]:
movie_similarity = cosine_similarity(rating_matrix.T)

movie_categories = candidateRatings["movieId"].astype("category")
movieId_lookup = movie_categories.cat.categories

if inputMovie_id not in movieId_lookup:
    print("The movie has no ratings, CF cannot be used")
else:
    print("CF can be used")

CF can be used

In [316]:
def get_top5_from_ratings(rating_matrix, ratings, inputMovie_id):
    movie_similarity = cosine_similarity(rating_matrix.T)

    movie_categories = ratings["movieId"].astype("category")
    movieId_lookup = movie_categories.cat.categories

    if inputMovie_id in movieId_lookup:
        input_index = list(movieId_lookup).index(inputMovie_id)

        similarities = movie_similarity[input_index]

    else:
        similarities = None

    sorted_sim_indx = np.argsort(similarities)[::-1]

    sim_movieIds = movieId_lookup[sorted_sim_indx]

    rec_Ids = sim_movieIds.drop(inputMovie_id)

    return movieDF.loc[movieDF["movieId"].isin(rec_Ids[:5]), "title"] #recommendations

In [317]:
if inputMovie_id in movieId_lookup:
    input_index = list(movieId_lookup).index(inputMovie_id)

    similarities = movie_similarity[input_index]

else:
    similarities = None

sorted_sim_indx = np.argsort(similarities)[::-1]

sim_movieIds = movieId_lookup[sorted_sim_indx]

rec_Ids = sim_movieIds.drop(inputMovie_id)

recommendations = movieDF.loc[movieDF["movieId"].isin(rec_Ids[:5]), "title"]

recommendations

4059                 See Spot Run
5200      Taking Care of Business
6436                    Curly Sue
8265    Christmas with the Kranks
9448              In Good Company
Name: title, dtype: str

In [318]:
def ranking(candidateIndex, inputMovieTitle):
    candRatings = get_ratings(candidateIndex, inputMovieTitle)
    rating_matrix = build_sparse_matrix(candRatings)

    inputMovie_id = movieTags.loc[movieTags["title"].str.lower() == inputMovieTitle.lower(), "movieId"].iloc[0]

    return get_top5_from_ratings(rating_matrix, candRatings, inputMovie_id)

In [354]:
def twostage_RetrievalRanking(movieTitle):

    if movieTitle[:3].lower() == "the":
        movieTitle = movieTitle[4:]+", the"

    candidatesIndx = rertieval(movieTitle, top_n=200)[1]

    return ranking(candidatesIndx, movieTitle)

In [389]:
twostage_RetrievalRanking("braveheart")

351            Forrest Gump
522        Schindler's List
582      Dances with Wolves
1939    Saving Private Ryan
3480              Gladiator
Name: title, dtype: str